### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by JACTERK**
Adds a Dockerfile based on Python3.11-slim to run the backend. Also changes main.py to print out the websocket port.

### CODE REVIEW

**Comment by linguini1** [comment]
Looks good to me. How does our ground station code get on this image to be run? This isn't run as a GitHub action, is it? Just for people to use to run it elsewhere?

**Review by linguini1 — APPROVED** [review]

**Comment by JACTERK** [comment]
> Looks good to me. How does our ground station code get on this image to be run? This isn't run as a GitHub action, is it? Just for people to use to run it elsewhere?

The code is copied from the directory the Dockerfile is in, so whatever code you have in your local ground-station folder will be put into the container

**Comment by linguini1** [comment]
> The code is copied from the directory the Dockerfile is in, so whatever code you have in your local ground-station folder will be put into the container

Okay great, so this will facilitate running the ground station on Docker locally for those who have Docker installed?

**Comment by JACTERK** [comment]
> > The code is copied from the directory the Dockerfile is in, so whatever code you have in your local ground-station folder will be put into the container
> 
> 
> 
> Okay great, so this will facilitate running the ground station on Docker locally for those who have Docker installed?

Yeah exactly, I'll look into how to get a GitHub action working to auto build an image when the main repo is updated, as well as update the wiki.

**Pull request merged**
